[package]
name = "pngme"
version = "0.1.0"
edition = "2021"
authors = ["von"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.0"
clap = {version = "3.2.22", features = ["derive"]}